// <auto-generated />
using System;
using DataAccess.Models.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AsistenteBDContext))]
    [Migration("20230526012021_asignacionTrueEnLosPensum_ASP_USER")]
    partial class asignacionTrueEnLosPensum_ASP_USER
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("DataAccess.Models.DB.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("DataAccess.Models.DB.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("DataAccess.Models.DB.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("AsignacionNueva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(1)))");

                    b.Property<bool>("AsignacionVieja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(1)))");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("DataAccess.Models.DB.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("DataAccess.Models.DB.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("DataAccess.Models.DB.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("DataAccess.Models.DB.Curso", b =>
                {
                    b.Property<string>("CursoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CrMin")
                        .HasColumnType("int");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Obligatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(0)))");

                    b.Property<bool>("PensumViejo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(0)))");

                    b.Property<string>("PreRequisitos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Semestre")
                        .HasColumnType("int");

                    b.HasKey("CursoId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            CursoId = "17",
                            CrMin = 0,
                            Creditos = 4,
                            Nombre = "SOCIAL HUMANISTICA 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = " ",
                            Semestre = 1
                        },
                        new
                        {
                            CursoId = "101",
                            CrMin = 0,
                            Creditos = 7,
                            Nombre = "MATE BASICA 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = " ",
                            Semestre = 1
                        },
                        new
                        {
                            CursoId = "69",
                            CrMin = 0,
                            Creditos = 3,
                            Nombre = "TECNICA COMPLEMENTARIA 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = " ",
                            Semestre = 1
                        },
                        new
                        {
                            CursoId = "39",
                            CrMin = 0,
                            Creditos = 1,
                            Nombre = "DEPORTES 1",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = " ",
                            Semestre = 1
                        },
                        new
                        {
                            CursoId = "348",
                            CrMin = 0,
                            Creditos = 3,
                            Nombre = "QUIMICA GENERAL 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = " ",
                            Semestre = 1
                        },
                        new
                        {
                            CursoId = "6",
                            CrMin = 0,
                            Creditos = 2,
                            Nombre = "IDIOMA TECNICO 1",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = " ",
                            Semestre = 1
                        },
                        new
                        {
                            CursoId = "19",
                            CrMin = 0,
                            Creditos = 4,
                            Nombre = "SOCIAL HUMANISTICA 2",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "17",
                            Semestre = 2
                        },
                        new
                        {
                            CursoId = "103",
                            CrMin = 0,
                            Creditos = 7,
                            Nombre = "MATE BASICA 2",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "101",
                            Semestre = 2
                        },
                        new
                        {
                            CursoId = "5",
                            CrMin = 0,
                            Creditos = 3,
                            Nombre = "TECNICAS DE ESTUDIO Y DE INVESTIGACION",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = " ",
                            Semestre = 2
                        },
                        new
                        {
                            CursoId = "147",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "FISICA BASICA",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "101",
                            Semestre = 2
                        },
                        new
                        {
                            CursoId = "40",
                            CrMin = 0,
                            Creditos = 1,
                            Nombre = "DEPORTES 2",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "39",
                            Semestre = 2
                        },
                        new
                        {
                            CursoId = "8",
                            CrMin = 0,
                            Creditos = 2,
                            Nombre = "IDIOMA TECNICO 2",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "101",
                            Semestre = 2
                        },
                        new
                        {
                            CursoId = "795",
                            CrMin = 33,
                            Creditos = 2,
                            Nombre = "LOGICA DE SISTEMAS",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "103",
                            Semestre = 3
                        },
                        new
                        {
                            CursoId = "960",
                            CrMin = 33,
                            Creditos = 5,
                            Nombre = "MATE COMPUTO 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "103",
                            Semestre = 3
                        },
                        new
                        {
                            CursoId = "770",
                            CrMin = 33,
                            Creditos = 4,
                            Nombre = "INTRODUCCION A LA PROGAMACION Y COMPUTACION 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "103",
                            Semestre = 3
                        },
                        new
                        {
                            CursoId = "107",
                            CrMin = 0,
                            Creditos = 10,
                            Nombre = "MATE INTERMEDIA 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "103",
                            Semestre = 3
                        },
                        new
                        {
                            CursoId = "150",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "FISICA 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "103,147",
                            Semestre = 3
                        },
                        new
                        {
                            CursoId = "9",
                            CrMin = 0,
                            Creditos = 2,
                            Nombre = "IDIOMA TECNICO 3",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "8",
                            Semestre = 3
                        },
                        new
                        {
                            CursoId = "732",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "ESTADISTICA 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "107,5",
                            Semestre = 4
                        },
                        new
                        {
                            CursoId = "796",
                            CrMin = 0,
                            Creditos = 3,
                            Nombre = "LENGUAJES FORMALES Y DE PROGRAMACION",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "770,795,960",
                            Semestre = 4
                        },
                        new
                        {
                            CursoId = "962",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "MATE COMPUTO 2",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "960,770,795",
                            Semestre = 4
                        },
                        new
                        {
                            CursoId = "771",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "INTRODUCCION A LA PROGRAMACION Y COMPUTACION 2",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "107,770,795,960",
                            Semestre = 4
                        },
                        new
                        {
                            CursoId = "10",
                            CrMin = 0,
                            Creditos = 2,
                            Nombre = "LOGICA",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "19",
                            Semestre = 4
                        },
                        new
                        {
                            CursoId = "112",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "MATE INTERMEDIA 2",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "107",
                            Semestre = 4
                        },
                        new
                        {
                            CursoId = "114",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "MATE INTERMEDIA 3",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "107",
                            Semestre = 4
                        },
                        new
                        {
                            CursoId = "152",
                            CrMin = 0,
                            Creditos = 6,
                            Nombre = "FISICA 2",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "107,150",
                            Semestre = 4
                        },
                        new
                        {
                            CursoId = "11",
                            CrMin = 0,
                            Creditos = 2,
                            Nombre = "IDIOMA TECNICO 4",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "9",
                            Semestre = 4
                        },
                        new
                        {
                            CursoId = "2025",
                            CrMin = 0,
                            Creditos = 0,
                            Nombre = "PRACTICA INICIAL",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "103,107",
                            Semestre = 4
                        },
                        new
                        {
                            CursoId = "736",
                            CrMin = 0,
                            Creditos = 4,
                            Nombre = "ANALISIS PROBABILISTICO",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "732",
                            Semestre = 5
                        },
                        new
                        {
                            CursoId = "777",
                            CrMin = 0,
                            Creditos = 4,
                            Nombre = "ORGANIZACION DE LENGUAJES Y COMPILADORES 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "771,796,962",
                            Semestre = 5
                        },
                        new
                        {
                            CursoId = "964",
                            CrMin = 0,
                            Creditos = 3,
                            Nombre = "ORGANIZACION COMPUTACIONAL",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "152,771,962",
                            Semestre = 5
                        },
                        new
                        {
                            CursoId = "772",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "ESTRUCTURA DE DATOS",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "771,796,962",
                            Semestre = 5
                        },
                        new
                        {
                            CursoId = "18",
                            CrMin = 90,
                            Creditos = 3,
                            Nombre = "FILOSOFIA DE LA CIENCIA",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "19",
                            Semestre = 5
                        },
                        new
                        {
                            CursoId = "116",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "MATE APLICADA 3",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "112,114",
                            Semestre = 5
                        },
                        new
                        {
                            CursoId = "118",
                            CrMin = 0,
                            Creditos = 6,
                            Nombre = "MATE APLICADA 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "112,114",
                            Semestre = 5
                        },
                        new
                        {
                            CursoId = "368",
                            CrMin = 0,
                            Creditos = 3,
                            Nombre = "PRINCIPIOS DE METROLOGIA",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "732,152,348",
                            Semestre = 5
                        },
                        new
                        {
                            CursoId = "650",
                            CrMin = 90,
                            Creditos = 3,
                            Nombre = "CONTABILIDAD 1",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = " ",
                            Semestre = 5
                        },
                        new
                        {
                            CursoId = "28",
                            CrMin = 90,
                            Creditos = 3,
                            Nombre = "ECOLOGIA",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = " ",
                            Semestre = 5
                        },
                        new
                        {
                            CursoId = "722",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "TEORIA DE SISTEMAS 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "732,772,116,118",
                            Semestre = 6
                        },
                        new
                        {
                            CursoId = "601",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "INVESTIGACION DE OPERACIONES 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "771,732",
                            Semestre = 6
                        },
                        new
                        {
                            CursoId = "14",
                            CrMin = 0,
                            Creditos = 4,
                            Nombre = "ECONOMIA",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "732",
                            Semestre = 6
                        },
                        new
                        {
                            CursoId = "781",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "ORGANIZACION DE LENGUAJES Y COMPILADORES 2",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "777,772",
                            Semestre = 6
                        },
                        new
                        {
                            CursoId = "778",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "ARQUITECTURA DE COMPUTADORES Y ENSAMBLADORES 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "796,964",
                            Semestre = 6
                        },
                        new
                        {
                            CursoId = "773",
                            CrMin = 0,
                            Creditos = 4,
                            Nombre = "MANEJO E IMPLEMENTACION DE ARCHIVOS",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "772,796",
                            Semestre = 6
                        },
                        new
                        {
                            CursoId = "122",
                            CrMin = 0,
                            Creditos = 4,
                            Nombre = "MATE APLICADA 4",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "118",
                            Semestre = 6
                        },
                        new
                        {
                            CursoId = "120",
                            CrMin = 0,
                            Creditos = 6,
                            Nombre = "MATE APLICADA 2",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "118",
                            Semestre = 6
                        },
                        new
                        {
                            CursoId = "200",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "ING. ELECTRICA 1",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "114,152",
                            Semestre = 6
                        },
                        new
                        {
                            CursoId = "652",
                            CrMin = 0,
                            Creditos = 3,
                            Nombre = "CONTABILIDAD 2",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "650",
                            Semestre = 6
                        },
                        new
                        {
                            CursoId = "335",
                            CrMin = 0,
                            Creditos = 3,
                            Nombre = "GESTION DE DESASTRES",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "28",
                            Semestre = 6
                        },
                        new
                        {
                            CursoId = "3662",
                            CrMin = 90,
                            Creditos = 0,
                            Nombre = "LEGISLACION 1",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = " ",
                            Semestre = 6
                        },
                        new
                        {
                            CursoId = "3022",
                            CrMin = 90,
                            Creditos = 0,
                            Nombre = "PSICOLOGIA INDUSTRIAL",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = " ",
                            Semestre = 6
                        },
                        new
                        {
                            CursoId = "724",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "TEORIA DE SISTEMAS 2",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "722,601,736",
                            Semestre = 7
                        },
                        new
                        {
                            CursoId = "603",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "INVETIGACION DE OPERACIONES 2",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "601",
                            Semestre = 7
                        },
                        new
                        {
                            CursoId = "734",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "ESTADISTICA 2",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "732",
                            Semestre = 7
                        },
                        new
                        {
                            CursoId = "281",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "SISTEMAS OPERATIVOS 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "781,778",
                            Semestre = 7
                        },
                        new
                        {
                            CursoId = "779",
                            CrMin = 0,
                            Creditos = 4,
                            Nombre = "ARQUITECTURA DE COMPUTADORAS Y ENSAMBLADORES 2",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "778",
                            Semestre = 7
                        },
                        new
                        {
                            CursoId = "970",
                            CrMin = 0,
                            Creditos = 4,
                            Nombre = "REDES DE COMPUTADORAS 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "773,778",
                            Semestre = 7
                        },
                        new
                        {
                            CursoId = "774",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "SISTEMAS DE BASES DE DATOS 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "773",
                            Semestre = 7
                        },
                        new
                        {
                            CursoId = "656",
                            CrMin = 150,
                            Creditos = 5,
                            Nombre = "ADMINISTRACION DE EMPRESAS 1",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = " ",
                            Semestre = 7
                        },
                        new
                        {
                            CursoId = "654",
                            CrMin = 0,
                            Creditos = 3,
                            Nombre = "CONTABILIDAD 3",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "652",
                            Semestre = 7
                        },
                        new
                        {
                            CursoId = "2036",
                            CrMin = 0,
                            Creditos = 0,
                            Nombre = "PRACTICA INTERMEDIA",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "778,777,773,2025",
                            Semestre = 7
                        },
                        new
                        {
                            CursoId = "3664",
                            CrMin = 0,
                            Creditos = 0,
                            Nombre = "LEGISLACION 2",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "3662",
                            Semestre = 7
                        },
                        new
                        {
                            CursoId = "3658",
                            CrMin = 0,
                            Creditos = 0,
                            Nombre = "ADMINISTRACION DE PERSONAL",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "3022",
                            Semestre = 7
                        },
                        new
                        {
                            CursoId = "700",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "INGENIERIA ECONOMICA 1",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "732",
                            Semestre = 7
                        },
                        new
                        {
                            CursoId = "285",
                            CrMin = 0,
                            Creditos = 4,
                            Nombre = "SISTEMAS OPERATIVOS 2",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "281",
                            Semestre = 8
                        },
                        new
                        {
                            CursoId = "975",
                            CrMin = 0,
                            Creditos = 4,
                            Nombre = "REDES DE COMPUTADORAS 2",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "970",
                            Semestre = 8
                        },
                        new
                        {
                            CursoId = "775",
                            CrMin = 0,
                            Creditos = 4,
                            Nombre = "SISTEMAS DE BASES DE DATOS 2",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "281,774",
                            Semestre = 8
                        },
                        new
                        {
                            CursoId = "283",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "ANALISIS Y DISENIO DE SISTEMAS 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "774",
                            Semestre = 8
                        },
                        new
                        {
                            CursoId = "797",
                            CrMin = 170,
                            Creditos = 3,
                            Nombre = "SEMINARIO DE SISTEMAS 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "724",
                            Semestre = 8
                        },
                        new
                        {
                            CursoId = "729",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "MODELACION Y SIMULACION 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "724,603",
                            Semestre = 9
                        },
                        new
                        {
                            CursoId = "786",
                            CrMin = 0,
                            Creditos = 4,
                            Nombre = "SISTEMAS ORGANIZACIONALES GERENZIALES 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "283,722",
                            Semestre = 9
                        },
                        new
                        {
                            CursoId = "972",
                            CrMin = 0,
                            Creditos = 4,
                            Nombre = "INTELIGENCIA ARTIFICIAL 1",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "781,775,724",
                            Semestre = 9
                        },
                        new
                        {
                            CursoId = "966",
                            CrMin = 0,
                            Creditos = 4,
                            Nombre = "SEGURIDAD Y AUDITORIA DE REDES",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "975",
                            Semestre = 9
                        },
                        new
                        {
                            CursoId = "785",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "ANALISIS Y DISENIO DE SISTEMAS 2",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "283",
                            Semestre = 9
                        },
                        new
                        {
                            CursoId = "788",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "SISTEMAS APLICADOS 1",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "283",
                            Semestre = 9
                        },
                        new
                        {
                            CursoId = "738",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "BASES DE DATOS AVANZADAS",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "775",
                            Semestre = 9
                        },
                        new
                        {
                            CursoId = "798",
                            CrMin = 190,
                            Creditos = 3,
                            Nombre = "SEMINARIO DE SISTEMAS 2",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "797",
                            Semestre = 9
                        },
                        new
                        {
                            CursoId = "288",
                            CrMin = 190,
                            Creditos = 4,
                            Nombre = "INTRODUCCION A LA EVALUACION DE IMPACTO AMBIENTAL",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = " ",
                            Semestre = 9
                        },
                        new
                        {
                            CursoId = "702",
                            CrMin = 0,
                            Creditos = 4,
                            Nombre = "INGENIERIA ECONOMICA 2",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "700",
                            Semestre = 9
                        },
                        new
                        {
                            CursoId = "1",
                            CrMin = 200,
                            Creditos = 4,
                            Nombre = "ETICA PROFESIONAL",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = " ",
                            Semestre = 9
                        },
                        new
                        {
                            CursoId = "2009",
                            CrMin = 200,
                            Creditos = 0,
                            Nombre = "PRACTICA FINAL",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "2036",
                            Semestre = 9
                        },
                        new
                        {
                            CursoId = "787",
                            CrMin = 0,
                            Creditos = 4,
                            Nombre = "SISTEMAS ORGANIZACIONALES Y GERENCIALES 2",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "786",
                            Semestre = 10
                        },
                        new
                        {
                            CursoId = "790",
                            CrMin = 0,
                            Creditos = 4,
                            Nombre = "EMPREDEDORES DE NEG. INFORMATICOS",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "786",
                            Semestre = 10
                        },
                        new
                        {
                            CursoId = "720",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "MODELACION Y SIMULACION 2",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "729",
                            Semestre = 10
                        },
                        new
                        {
                            CursoId = "968",
                            CrMin = 0,
                            Creditos = 4,
                            Nombre = "INTELIGENCIA ARTIFICIAL 2",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "972",
                            Semestre = 10
                        },
                        new
                        {
                            CursoId = "974",
                            CrMin = 0,
                            Creditos = 4,
                            Nombre = "REDES DE NUEVA GENERACION",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "975",
                            Semestre = 10
                        },
                        new
                        {
                            CursoId = "780",
                            CrMin = 0,
                            Creditos = 6,
                            Nombre = "SOFTWARE AVANZADO",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "785",
                            Semestre = 10
                        },
                        new
                        {
                            CursoId = "789",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "SISTEMAS APLICADOS 2",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "785,788",
                            Semestre = 10
                        },
                        new
                        {
                            CursoId = "735",
                            CrMin = 0,
                            Creditos = 5,
                            Nombre = "AUDITORIA DE PROYECTOS DE SOFTWARE",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "785",
                            Semestre = 10
                        },
                        new
                        {
                            CursoId = "7990",
                            CrMin = 225,
                            Creditos = 4,
                            Nombre = "SEMINARIO DE INVESTIGACION EPS",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = " ",
                            Semestre = 10
                        },
                        new
                        {
                            CursoId = "710",
                            CrMin = 190,
                            Creditos = 6,
                            Nombre = "PLANEAMIENTO",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = " ",
                            Semestre = 10
                        },
                        new
                        {
                            CursoId = "706",
                            CrMin = 190,
                            Creditos = 4,
                            Nombre = "PREPARACION Y EVALUACION DE PROYECTOS 1",
                            Obligatorio = false,
                            PensumViejo = true,
                            PreRequisitos = "700",
                            Semestre = 10
                        },
                        new
                        {
                            CursoId = "799",
                            CrMin = 220,
                            Creditos = 3,
                            Nombre = "SEMINARIO DE INVESTIGACION",
                            Obligatorio = true,
                            PensumViejo = true,
                            PreRequisitos = "798",
                            Semestre = 10
                        });
                });

            modelBuilder.Entity("DataAccess.Models.DB.Relacion", b =>
                {
                    b.Property<string>("RelacionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AspNetUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("color");

                    b.Property<string>("CursoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.HasKey("RelacionId");

                    b.HasIndex(new[] { "AspNetUserId" }, "IX_Relacion_AspNetUserId");

                    b.HasIndex(new[] { "CursoId" }, "IX_Relacion_CursoId");

                    b.ToTable("Relacion", (string)null);
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.HasOne("DataAccess.Models.DB.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Models.DB.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Models.DB.AspNetRoleClaim", b =>
                {
                    b.HasOne("DataAccess.Models.DB.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DataAccess.Models.DB.AspNetUserClaim", b =>
                {
                    b.HasOne("DataAccess.Models.DB.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccess.Models.DB.AspNetUserLogin", b =>
                {
                    b.HasOne("DataAccess.Models.DB.AspNetUser", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccess.Models.DB.AspNetUserToken", b =>
                {
                    b.HasOne("DataAccess.Models.DB.AspNetUser", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccess.Models.DB.Relacion", b =>
                {
                    b.HasOne("DataAccess.Models.DB.AspNetUser", "AspNetUser")
                        .WithMany("Relacions")
                        .HasForeignKey("AspNetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Models.DB.Curso", "Curso")
                        .WithMany("Relacions")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AspNetUser");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("DataAccess.Models.DB.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("DataAccess.Models.DB.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserTokens");

                    b.Navigation("Relacions");
                });

            modelBuilder.Entity("DataAccess.Models.DB.Curso", b =>
                {
                    b.Navigation("Relacions");
                });
#pragma warning restore 612, 618
        }
    }
}
